[color]
background = 'default'
foreground = '#80d4d5'

; gradient = 0
gradient = 1
gradient_color_1 = '#004f50'
gradient_color_2 = '#80d4d5'
gradient_color_3 = '#9cf1f2'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#004f50'
horizontal_gradient_color_2 = '#80d4d5'
horizontal_gradient_color_3 = '#9cf1f2'
horizontal_gradient_color_4 = '#80d4d5'
horizontal_gradient_color_5 = '#004f50'


