[color]
background = 'default'
foreground = '#f0bf6d'

; gradient = 0
gradient = 1
gradient_color_1 = '#604100'
gradient_color_2 = '#f0bf6d'
gradient_color_3 = '#ffdeac'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#604100'
horizontal_gradient_color_2 = '#f0bf6d'
horizontal_gradient_color_3 = '#ffdeac'
horizontal_gradient_color_4 = '#f0bf6d'
horizontal_gradient_color_5 = '#604100'


