-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#17130b',
  base01 = '#120d07',
  base02 = '#201b13',
  base03 = '#4e4539',
  base04 = '#d2c5b4',
  base05 = '#ece1d4',
  base06 = '#362f27',
  base07 = '#3f382f',

  base08 = '#ffb4ab',
  base09 = '#b5cea4',
  base0A = '#dbc3a1',
  base0B = '#f0bf6d',
  base0C = '#374c2d',
  base0D = '#604100',
  base0E = '#55442a',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#604100',
  fg = '#17130b',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#d0eabf',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#b5cea4',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#dbc3a1',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#7c580d',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#120d07',
  fg = '#f0bf6d',
})
