#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -a firefox desktop='^I' follow=on
bspc rule -a chromium desktop='^I' follow=on
bspc rule -a telegram-desktop desktop='^II' follow=on
bspc rule -a discord desktop='^II' follow=on
bspc rule -a thunar desktop='^III' follow=on
bspc rule -a Alacritty desktop='^III' follow=on
bspc rule -a code desktop='^IV' follow=on
bspc rule -a spotify desktop='^V' state=floating follow=on center=on
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating
bspc rule -a qimgv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

nitrogen --restore
systemctl --user enable opentabletdriver.service --now
picom --config ~/.config/picom/picom.conf &
$HOME/.screenlayout/display.sh
$HOME/.config/polybar/launch.sh