#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -a Firefox desktop='^1'
bspc rule -a Discord desktop='^2'
bspc rule -a vesktop desktop='^2'
bspc rule -a TelegramDesktop desktop='^2'
bspc rule -a AyuGramDesktop desktop='^2'
bspc rule -a Code desktop='^4'
bspc rule -a obsidian desktop='^4'
bspc rule -a Spotify desktop='^5'
bspc rule -a mpv desktop='^5'
bspc rule -a osu!.exe desktop='^6'

dunst &
nitrogen --restore
systemctl --user enable opentabletdriver.service --now
picom --config ~/.config/picom/picom.conf &
# $HOME/.screenlayout/display.sh
$HOME/.config/polybar/launch.sh
sudo rmmod wacom
udiskie &