#Gaps
gappih=6
gappiv=6
gappoh=8
gappov=8

#Borders
borderpx=0
border_radius=24
no_border_when_single=1
no_radius_when_single=0

#Opacity
focused_opacity=1.0
unfocused_opacity=1.0

#Blur
blur=1
blur_layer=1

blur_params_radius=6
blur_params_num_passes=3
blur_optimized=1

blur_params_brightness=0.85
blur_params_contrast=0.9
blur_params_saturation=1.0
blur_params_noise=0.02

#Shadows
shadows=1
layer_shadows=1
shadow_only_floating=1
shadows_size=18
shadows_blur=15
shadows_position_x=0
shadows_position_y=6
shadowscolor=0x00000040

#Animations
animations=1
layer_animations=1
animation_type_open=slide
animation_type_close=slide
animation_fade_in=1
animation_fade_out=1
tag_animation_direction=1

zoom_initial_ratio=0.82
zoom_end_ratio=1.02
fadein_begin_opacity=0.0
fadeout_begin_opacity=1.0

animation_duration_open=350
animation_duration_close=220
animation_duration_move=320
animation_duration_tag=380
animation_duration_focus=180

animation_curve_open=0.05,1.15,0.15,1.0
animation_curve_close=0.0,0.0,0.15,1.0
animation_curve_move=0.08,1.12,0.18,1.02
animation_curve_tag=0.05,1.15,0.15,1.02
animation_curve_focus=0.0,0.0,0.15,1.0
animation_curve_opafadein=0.05,1.15,0.15,1.0
animation_curve_opafadeout=0.0,0.0,0.15,1.0