#Autostart
exec-once=awww-daemon
exec-once=/usr/lib/xdg-desktop-portal-wlr &
exec-once=gsr-ui
exec-once=sudo chown $USER:$USER -R $HOME
exec-once=udiskie &
exec-once=systemctl --user start hyprpolkitagent
exec-once=/lib/xdg-desktop-portal
exec-once=systemctl --user start opentabletdriver.service
exec-once=rmmod wacom
exec-once=wl-paste --watch cliphist store
exec-once=wl-paste --type text --watch cliphist -max-items=50 store
exec-once=wl-paste --type image --watch cliphist -max-items=50 store
exec-once=gsettings set org.gnome.desktop.interface cursor-theme Bibata-Modern-Ice
exec-once=$HOME/.config/waybar/mangowm/launch.sh
exec-once=bash ~/.config/mango/idle.sh