#Applications
bind=SUPER,Return,spawn,kitty
bind=SUPER+SHIFT,Return,spawn,kitty --class floatterm
bind=SUPER,e,spawn,kitty yazi
bind=SUPER+SHIFT,e,spawn,kitty --class floatterm yazi
bind=SUPER,n,spawn,code
bind=SUPER,w,spawn,helium-browser
# bind=SUPER,t,spawn,waypaper
bind=SUPER,b,spawn,spotify
bind=SUPER,d,spawn,$HOME/.config/rofi/launcher/launcher.sh
bind=SUPER,v,spawn,$HOME/.config/rofi/clipboard/clipboard.sh
bind=SUPER,l,spawn,hyprlock
bind=SUPER,0,spawn,better-control

#Window Management
bind=SUPER,q,killclient
bind=SUPER,s,togglefloating
bind=SUPER,f,togglefullscreen
bind=SUPER+SHIFT,e,spawn,wlogout
bind=SUPER+SHIFT,r,reload_config
bind=SUPER+SHIFT,M,quit

#Focus Navigation
bind=SUPER,Left,focusdir,left
bind=SUPER,Down,focusdir,down
bind=SUPER,Up,focusdir,up
bind=SUPER,Right,focusdir,right
bind=SUPER,h,focusdir,left
bind=SUPER,j,focusdir,down
bind=SUPER,k,focusdir,up
# bind=SUPER,l,focusdir,right
bind=SUPER,Tab,focusstack,next
bind = ALT,Tab,view, -1
bind=SUPER+SHIFT,Tab,focusstack,prev

#Window Exchange
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Right,exchange_client,right
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,l,exchange_client,right

#Window Resize
bind=SUPER+CTRL,Left,resizewin,-20,0
bind=SUPER+CTRL,Right,resizewin,20,0
bind=SUPER+CTRL,Up,resizewin,0,-20
bind=SUPER+CTRL,Down,resizewin,0,20
bind=SUPER+CTRL,h,resizewin,-20,0
bind=SUPER+CTRL,l,resizewin,20,0
bind=SUPER+CTRL,k,resizewin,0,-20
bind=SUPER+CTRL,j,resizewin,0,20

#Tags/Workspaces
bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9
bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9

#Gestures
gesturebind=none,left,3,viewtoleft_have_client
gesturebind=none,right,3,viewtoright_have_client
gesturebind=none,up,3,toggleoverview
gesturebind=none,down,3,toggleoverview

#Layouts
bind=SUPER,space,switch_layout
bind=SUPER+SHIFT,t,setlayout,dwindle
bind=SUPER,t,setlayout,tile
bind=SUPER,a,setlayout,scroller
bind=SUPER,m,setlayout,monocle
bind=SUPER,o,toggleoverview

# bind=SUPER,v,setoption,tag_animation_direction,0
# bind=SUPER+SHIFT,v,setoption,tag_animation_direction,1
bind=SUPER,g,togglegaps
bind=SUPER+SHIFT,g,toggleglobal
bind=SUPER,bracketleft,setmfact,-0.05
bind=SUPER,bracketright,setmfact,+0.05
bind=SUPER,r,switch_proportion_preset

#Screenshots & Media
bind=NONE,Print,spawn_shell,grim - | tee ~/pictures/screenshots/$(date +%Y-%m-%d_%H-%M-%S).png | wl-copy && notify-send "screenshot" "screen captured"
bind=SUPER+SHIFT,s,spawn_shell,grim -g "$(slurp)" - | tee ~/pictures/screenshots/$(date +%Y-%m-%d_%H-%M-%S).png | wl-copy && notify-send "screenshot" "area captured"
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05-
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.05+
bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl set +5%
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl set 5%-

#Mouse & Axis Binds
bind=SUPER+CTRL,r,reload_config
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client