[general]
import = [
    "~/.config/alacritty/themes/themes/kripton.toml"
]

[window]
decorations = "none"
opacity = 1
blur = true
startup_mode = "Windowed"
title = "terminal"
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
size = 12
offset = { x = 0, y = 0 }

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true