# : Manager [[[

[mgr]
cwd = { fg = "#ece1d4" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#98d172", bg = "#98d172" }
marker_cut      = { fg = "#d0eabf", bg = "#d0eabf" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#b5cea4", bg = "#b5cea4" }

# Count
count_copied   = { fg = "#0d2005", bg = "#d0eabf" }
count_cut      = { fg = "#0d2005", bg = "#d0eabf" }
count_selected = { fg = "#432c00", bg = "#b5cea4" }

# Border
border_symbol = "│"
border_style  = { fg = "#f0bf6d" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "", close = "" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#f0bf6d", bold = true, bg = "#17130b" }
inactive  = { fg = "#dbc3a1", bg = "#17130b" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#f0bf6d", fg = "#432c00", bold = true }
normal_alt  = { bg = "#4e4539", fg = "#d2c5b4" }

# Select mode
select_main = { bg = "#dbc3a1", fg = "#3d2e16", bold = true }
select_alt  = { bg = "#4e4539", fg = "#d2c5b4" }

# Unset mode
unset_main = { bg = "#b5cea4", fg = "#213618", bold = true }
unset_alt  = { bg = "#4e4539", fg = "#d2c5b4" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_type  = { fg = "#a47a3f" }
perm_write = { fg = "#668d4c" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#7bc44c" }
perm_sep   = { fg = "#ffa113" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#f0bf6d", bg = "#3f382f" }
progress_error  = { fg = "#ffb4ab", bg = "#3f382f" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3f382f" }
cand = { fg = "#f0bf6d" }
rest = { fg = "#432c00" }
desc = { fg = "#ece1d4" }
separator = " ▶ "
separator_style = { fg = "#ece1d4" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#b5cea4" }
title_warn  = { fg = "#f0bf6d" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#f0bf6d" }
active = { fg = "#b5cea4", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#f0bf6d" }
value  = { fg = "#ece1d4" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#f0bf6d", bg = "#432c00" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#f0bf6d" }
title   = {}
hovered = { fg = "#d0eabf", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#ece1d4" }
run    = { fg = "#ece1d4" }
footer = { fg = "#3d2e16", bg = "#dbc3a1" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#ece1d4" },
    { url = "*/", fg = "#f0bf6d" },
]

# : ]]]
