[mgr]
sort_by        = "mtime"
sort_reverse   = true
sort_dir_first = true
show_hidden    = false
mouse_events = [ "click", "scroll", "touch", "move", "drag" ]

[theme]
use = "theme"

[icons]
enabled = true

[plugin]
prepend_previewers = [
    # archives (zip, rar, 7z, tar)
    { url = "*.tar.gz", run = "ouch" },
    { url = "*.tar.xz", run = "ouch" },
    { url = "*.zip",    run = "ouch" },
    { url = "*.7z",     run = "ouch" },
    { url = "*.rar",    run = "ouch" },
    
    # office
    { url = "*.docx", run = "office" },
    { url = "*.pptx", run = "office" },
    { url = "*.xlsx", run = "office" },
    
    # pretty code and json
    { url = "*.md",   run = "rich-preview" },
    { url = "*.json", run = "rich-preview" },
    { url = "*.csv",  run = "rich-preview" },
    { url = "*.py",   run = "rich-preview" },
    { url = "*.js",   run = "rich-preview" },
    { url = "*.rs",   run = "rich-preview" },
    { url = "*.go",   run = "rich-preview" },

    # audio
    { mime = "audio/*", run = "audio-preview" },
]
