# Mango Conf.dig :D
source=~/.config/mango/conf.d/appearance.conf
source=~/.config/mango/conf.d/autostart.conf
source=~/.config/mango/conf.d/binds.conf
source=~/.config/mango/conf.d/colors.conf
source=~/.config/mango/conf.d/input.conf
source=~/.config/mango/conf.d/layouts.conf
source=~/.config/mango/conf.d/monitors.conf
source=~/.config/mango/conf.d/windowrules.conf
